#!/usr/bin/env python3
"""
generate_matrix.py

Generates a 2x2 scenario matrix in Markdown format from a JSON configuration.

Usage:
    python generate_matrix.py [config.json] [output.md]
    
    Defaults to scenarios_config.json and outputs to stdout or specified file.
"""

import json
import sys
from pathlib import Path


DEFAULT_CONFIG = {
    "title": "AI Governance Futures (2024-2030)",
    "axis_x": {
        "name": "AI Capability Trajectory",
        "left": "Incremental",
        "right": "Discontinuous"
    },
    "axis_y": {
        "name": "Global Regulatory Coherence", 
        "top": "Harmonized",
        "bottom": "Fragmented"
    },
    "scenarios": {
        "top_left": {
            "name": "Coordinated Caution",
            "tagline": "Global guardrails before the leap",
            "probability": 20
        },
        "top_right": {
            "name": "Emergency Coordination",
            "tagline": "Crisis forces cooperation",
            "probability": 15
        },
        "bottom_left": {
            "name": "Patchwork Progress",
            "tagline": "Steady advance, messy governance",
            "probability": 45
        },
        "bottom_right": {
            "name": "Fragmented Scramble",
            "tagline": "Transformative AI, unprepared world",
            "probability": 20
        }
    }
}


def generate_matrix_ascii(config: dict) -> str:
    """Generate ASCII art 2x2 matrix."""
    
    ax = config["axis_x"]
    ay = config["axis_y"]
    sc = config["scenarios"]
    
    # Scenario names (truncate if needed)
    tl = sc["top_left"]["name"][:18].center(18)
    tr = sc["top_right"]["name"][:18].center(18)
    bl = sc["bottom_left"]["name"][:18].center(18)
    br = sc["bottom_right"]["name"][:18].center(18)
    
    matrix = f"""
                        {ay["top"].upper()}
                           ▲
                           │
         ┌─────────────────┼─────────────────┐
         │                 │                 │
         │{tl}│{tr}│
         │                 │                 │
{ax["left"].upper():^12} ◄──────────────┼────────────────► {ax["right"].upper()}
         │                 │                 │
         │{bl}│{br}│
         │                 │                 │
         └─────────────────┼─────────────────┘
                           │
                           ▼
                        {ay["bottom"].upper()}
"""
    return matrix


def generate_markdown(config: dict) -> str:
    """Generate full Markdown output."""
    
    lines = []
    
    # Title
    lines.append(f"# Scenario Matrix: {config['title']}\n")
    
    # Axes description
    lines.append("## Axes\n")
    lines.append(f"**X-Axis:** {config['axis_x']['name']}")
    lines.append(f"- Left: {config['axis_x']['left']}")
    lines.append(f"- Right: {config['axis_x']['right']}\n")
    lines.append(f"**Y-Axis:** {config['axis_y']['name']}")
    lines.append(f"- Top: {config['axis_y']['top']}")
    lines.append(f"- Bottom: {config['axis_y']['bottom']}\n")
    
    # ASCII Matrix
    lines.append("## Matrix\n")
    lines.append("```")
    lines.append(generate_matrix_ascii(config))
    lines.append("```\n")
    
    # Scenario table
    lines.append("## Scenarios\n")
    lines.append("| Quadrant | Scenario | Tagline | Probability |")
    lines.append("|----------|----------|---------|-------------|")
    
    quadrant_labels = {
        "top_left": f"{config['axis_x']['left']} + {config['axis_y']['top']}",
        "top_right": f"{config['axis_x']['right']} + {config['axis_y']['top']}",
        "bottom_left": f"{config['axis_x']['left']} + {config['axis_y']['bottom']}",
        "bottom_right": f"{config['axis_x']['right']} + {config['axis_y']['bottom']}"
    }
    
    for quad, label in quadrant_labels.items():
        sc = config["scenarios"][quad]
        lines.append(f"| {label} | **{sc['name']}** | {sc['tagline']} | {sc['probability']}% |")
    
    # Probability check
    total_prob = sum(config["scenarios"][q]["probability"] for q in config["scenarios"])
    lines.append(f"\n*Total probability: {total_prob}%*\n")
    
    # Generation note
    lines.append("---")
    lines.append("*Generated by generate_matrix.py*")
    
    return "\n".join(lines)


def main():
    # Load config
    if len(sys.argv) > 1 and Path(sys.argv[1]).exists():
        with open(sys.argv[1]) as f:
            config = json.load(f)
    else:
        config = DEFAULT_CONFIG
        # Also write default config for reference
        config_path = Path(__file__).parent / "scenarios_config.json"
        with open(config_path, "w") as f:
            json.dump(DEFAULT_CONFIG, f, indent=2)
    
    # Generate markdown
    output = generate_markdown(config)
    
    # Write or print
    if len(sys.argv) > 2:
        with open(sys.argv[2], "w") as f:
            f.write(output)
        print(f"Matrix written to {sys.argv[2]}")
    else:
        print(output)


if __name__ == "__main__":
    main()
